let g:floaterm_keymap_new = '<Leader>tn'
let g:floaterm_keymap_prev = '<Leader>tp'
let g:floaterm_keymap_next = '<Leader>tP'
let g:floaterm_keymap_hide = '<Leader>th'
let g:floaterm_keymap_kill = '<Leader>tk'
let g:floaterm_keymap_toggle = '<Leader>tt'
